version: '3'

services:
  backend:
    restart: always
    build: ./backend
    environment:
        - GIN_MODE=release
    expose:
      - "8080"
    networks:
      - kasaz
      
  nginx:
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/var/staticfiles
    ports:
      - "8080:80"
    links:
      - backend:backend
    networks:
      - kasaz


volumes:
  staticfiles:

networks:
  kasaz:
